import torch
from TDnCNN import DnCNN_3D
from torch.optim import AdamW
from torchvision import transforms
from torch.utils.data import DataLoader, random_split
from dataset import MultiRoadDataset, SubbandSelect, Freq2Delay, Antenna2Beam
from tools import get_noise

# Actual signal preprocessing
transform_pipe = transforms.Compose([
    SubbandSelect(N_subbands=17, method='random'),
    Freq2Delay(inverse=False),
    # HardWindow(left=13, right=3),
    Antenna2Beam(N_pol=2, N_hor=8, N_ver=4, inverse=False)
])

def train(model, device, train_loader, optimizer, epoch, SNR_dB=0, log_interval=1):
    model.train()
    for batch_idx, H_batch in enumerate(train_loader):

        Noise_batch = get_noise(H_batch, SNR_dB=SNR_dB)

        H_batch, Noise_batch = H_batch.to(device), Noise_batch.to(device)
        optimizer.zero_grad()

        H_noisy = H_batch + Noise_batch
        H_pred = model(H_noisy)

        mse = (H_pred - H_batch).abs().pow(2).sum() / 10

        mse.backward()
        optimizer.step()
        if batch_idx % log_interval == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * len(H_batch), len(train_loader.dataset),
                       100. * batch_idx / len(train_loader), mse.item()))


def test(model, device, test_loader, SNR_dB=0):
    model.eval()
    Mse = 0
    with torch.no_grad():
        for H_batch in test_loader:
            Noise_batch = get_noise(H_batch, SNR_dB=SNR_dB)

            H_batch, Noise_batch = H_batch.to(device), Noise_batch.to(device)
            H_noisy = H_batch + Noise_batch

            H_pred = model(H_noisy)

            mse = (H_pred - H_batch).abs().pow(2).sum().item()
            Mse += mse
    print(Mse / len(test_loader))


if __name__ == '__main__':
    test_ratio = 0.2
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    # path to file generated by Quadriga channel model
    pathlist = ['/Users/albly/GitHub/MIMO_road_generator/data/channel_seed_231.mat',
                '/Users/albly/GitHub/MIMO_road_generator/data/channel_seed_232.mat']

    # Actual signal preprocessing
    transform_pipe = transforms.Compose([
        SubbandSelect(N_subbands=17, method='random'),
        Freq2Delay(inverse=False),
        # HardWindow(left=13, right=3),
        Antenna2Beam(N_pol=2, N_hor=8, N_ver=4, inverse=False)
    ])

    dataset = MultiRoadDataset(paths=pathlist, transform=transform_pipe)
    N_samples = len(dataset)
    N_test_samples = int(N_samples * test_ratio)
    N_train_samples = N_samples - N_test_samples

    dataset_train, dataset_test = random_split(dataset, [N_train_samples, N_test_samples])

    train_loader = DataLoader(
        dataset_train,
        batch_size=10,
        shuffle=False,
        pin_memory=True,
        #prefetch_factor=5,
        num_workers=5,
    )

    test_loader = DataLoader(
        dataset_test,
        batch_size=10,
        shuffle=False,
        pin_memory=True,
        #prefetch_factor=5,
        #num_workers=20,

    )

    model = DnCNN_3D(channels=8,
                     num_of_layers=15,
                     num_features=64).to(device)

    optimizer = AdamW(model.parameters(), lr=1e-4)

    for i_epoch in range(1):
        train(model, device, train_loader, optimizer, i_epoch)
        test(model, device, test_loader)