defaults:
  - _self_

seed: 42

# train noisy dataset
dataset_path: "./data/dataset_noisy/dataset_noisy.h5"

# Папка, куда сохранится обученная модель
id_label: ''
output_dir: "./models/TDnCNN_model${.id_label}"

# TDnCNN noise
AWGN_params:
    snr_db_range: [-20, 0] # min_snr, max_snr

# Параметры модели
model_size: 'large' # ['small', 'large']

# Dataloader
batch_size: 32
num_workers: 4
in_memory: True

# train loop
lr: 1e-4
sheduler_mode: 'plateau'  # ['warmup', 'cos', 'comb', 'plateau', None]

# Параметры для sheduler_mode = 'plateau'
plateau_params:
    patience: 10
    threshold: 0.01
    factor: 0.5
warmup_params:
    threshold: 0.1 #10%
    
grad_clip_val: 1000
n_epochs: 50
patience: 10

save_interval: 1