defaults:
  - _self_


seed: 42                 

# Путь к исходным .mat файлам
input_dir: "./data/train" 

# Папка, куда сохранится dataset_clean.h5
output_dir: "../data/dataset_train"

# -----------------------------------------------------------------------------
# Параметры трансформеров (преобразования от заказчика)

transforms_params:
  SubbandSelect:
    N_subbands: 17            # Количество поддиапазонов частот
    method: 0         # Метод выборки (проверь допустимые значения в классе SubbandSelect)

  Antenna2Beam:
    N_pol: 2                  # Количество поляризаций
    N_hor: 8                  # Количество антенных элементов по горизонтали
    N_ver: 4                  # Количество антенных элементов по вертикали

# -----------------------------------------------------------------------------
# Параметры сохранения (save_params)

save_params:
  batch_size: 16              # Размер пачки данных при чтении и записи. 
                              # Чем больше, тем быстрее, но нужно больше RAM.
  
  log_threshold: 10           # Как часто писать в лог (в процентах). 
                              # Например, 10 означает сообщения каждые 10%.
  
  num_workers: 0              # НЕ РАБОТАЕТ !