defaults:
  - _self_

seed: 42

# memmap dataset
dataset_path: "./data/dataset_noisy/dataset_noisy.h5"

# Где храняться обученные параметры
checkpoint_dir: './models/DDPM_model'
checkpoint_name: ''

# Dataloader
batch_size: 32
num_workers: 4
in_memory: True

# train loop
lr: 1e-4
n_epochs: 30
patience: 10
grad_clip_val: 100000
sheduler_mode: 'plateau'  # ['warmup', 'cos', 'comb', 'plateau', None]

optimizer_load: True

# Параметры для sheduler_mode = 'plateau'
plateau_params:
    patience: 5
    threshold: 0.001
    factor: 0.5

warmup_params:
    threshold: 0.1 #10%


save_interval: 'last_only'