defaults:
  - _self_
  - hydra: hydra_config
  - dataset: mnist
  - train_latent_DDPM: default
  - filter_dataset: default

project:
    id: "exp_001"

logName: "main"

task: "train_latent_DDPM"

# all tasks:
    # train_latent_DDPM
    # filter_dataset
