defaults:
  - _self_

seed: 42 

# Путь к исходному чистому датасету (.h5)
input_data_path: "../data/dataset_train/dataset_clean.h5"

# -----------------------------------------------------------------------------
# Папка для сохранения результата
output_dir: "./data/dataset_noisy"

# Имя выходного файла
output_data_file: "dataset_noisy.h5"

# Полный путь к выходному файлу. 
output_data_path: "${.output_dir}/${.output_data_file}"

# -----------------------------------------------------------------------------
# Параметры шума (AWGN)
AWGN_params:
    RW_scenario: True # Real-world scenario 
    snr_db_range: [0, 0]  # SNR, dB. [min, max]. If RW_scenario is False

# -----------------------------------------------------------------------------
# Параметры сохранения и логирования
save_params:
    log_threshold: 10       # Как часто выводить лог (каждые 10% прогресса)