defaults:
  - _self_

seed: 42                 


# test preprocessed dataset
dataset_path: "../data/dataset_test/dataset_clean.h5"
input_model_dir: "./models/TDnCNN_model"


# Папка, куда сохранится
output_dir: "./outputs"
output_fname: "gap_metric_results"

# Noise SNR
AWGN_params:
    RW_scenario: False
    snr_db_range: [-10, -10] # min_snr, max_snr

    
# Доп. параметры
N_batch_size: 16
limit_batches: 100
in_memory: True
num_workers: 0